---
output:
  pagedown::html_paged:
    css: ["css/one-column-paged-academic.css",  "https://use.fontawesome.com/releases/v5.7.2/css/all.css"]
    number_sections: false
links-to-footnotes: true
knit: pagedown::chrome_print
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(knitr)
library(lubridate)
library(glue)

######## CREATE HELPER FUNCTIONS
# function which takes a name and replaces the first name with initial and dot
replace_first_name_with_initial_and_dot <- function(author_name) {
  str_replace(author_name, "(?<=\\S)\\S+", "\\.")
}

# function for doing this for an entry with a number of authors
replace_first_names_in_list_with_initial_and_dot <- function(authors){
  authors_split <- str_split(authors, ",") %>% 
    map(str_trim)
  
  authors_split[[1]] %>% map_chr(replace_first_name_with_initial_and_dot) %>% 
    paste0(collapse = ", ")
}

# function for adding leading zero's when there's more than 10 entries
padding_function <- function(cv_entries_tibble, letter_to_pad){
  if(nrow(cv_entries_tibble) > 9){
    cv_entries_tibble %>% 
      arrange(date) %>%
  mutate(number = str_pad(row_number(), width = 2, side = "left", pad = "0"),
         number = str_c(letter_to_pad, number)) %>%
  arrange(desc(date))
  } else {
    cv_entries_tibble %>% 
      arrange(date) %>%
  mutate(number = str_pad(row_number(), width = 1, side = "left", pad = "0"),
         number = str_c(letter_to_pad, number)) %>%
  arrange(desc(date))
  }
}

# function for making a year blank when it's the same as the one preceding it
blank_year_when_repeated <- function(cv_entry_tibble){
  cv_entry_tibble %>% 
    mutate(row_number = row_number()) %>% 
    mutate(year = as.character(year),
           year = case_when(
             row_number == 1 ~ year,
             year == lag(year) ~ "",
             year != lag(year) ~ year
           )) %>% 
    select(-row_number)
}


####### READ IN DATA
#### publications #####
publications <- read_csv("_content/publications.csv") %>%
  mutate(date = as.Date(date, format = "%d/%m/%Y")) %>%
  mutate(authors_full = map_chr(authors_full, replace_first_names_in_list_with_initial_and_dot)) %>% 
  mutate(authors_full = str_replace(authors_full, "L\\. Heron", "*L\\. Heron*")) %>%    # make my name italic
  mutate(year = year(date)) %>% 
  mutate(venue_abbrev = if_else(!is.na(venue_abbrev), str_c(venue_abbrev, ": "), "")) # make the abbrevation an empty string if NA; add a colon and a space after if it if there is one

#### cv entries #####
cv_entries <- read_csv("_content/cv_entries.csv") %>% 
  mutate(date = as.Date(date, format = "%d/%m/%Y")) %>%
  mutate(year = year(date)) %>%
  mutate(year_end = case_when(
    date_end == "present" ~ date_end,
    !is.na(date_end) ~ str_sub(date_end, 7, 10),
    is.na(date_end) ~ date_end
  )) %>%
  mutate(year = ifelse((is.na(year_end) | year == year_end),
                      year,
                      str_c(year, " --- ", year_end)))

```


```{css}
:root{
  --last-updated: " \00a0 \00a0 \00a0 \00a0 Last updated: May 2022";
}
```



:::::: {.title-and-contact}

::: {.title}
<h1 class="title">Leonie Heron</h1>
:::

::: {.contact-info}
leonie.heron@ispm.unibe.ch  \
Tel: +41765349161
:::

::::::

<div class="cv-entries">
## Research positions
```{r}
cv_entries %>% 
  filter(type == 'research_positions', is.na(exclude)) %>%
  mutate(what = glue("<span class='cv-entry-title'>{what}</span><br>",
                     "{where}"
                     )) %>% 
  select(year, what) %>% 
  kable()
```
## Education
```{r}
cv_entries %>% 
  filter(type == 'education') %>% 
  mutate(what = glue("<span class='cv-entry-title'>{what}</span>, {where}<br>", 
                      "{additional_info}<br>",
                      "<span class='thesis-title'>{additional_info2}</span>")) %>% 
  select(year, what) %>% 
  kable()
```
```{r}
### Major grants and funding
cv_entries %>%
  filter(type == 'major_grants') %>%
  mutate(what = if_else(is.na(additional_info),
                        glue("<span class='cv-entry-title'>{what}</span> ({additional_info2}), {where}"),
                        glue("<span class='cv-entry-title'>{what}</span> ({additional_info2}), {where}.<br>{additional_info}"))) %>%
  select(year, what) %>%
  kable()
```
## Work
```{r}
cv_entries %>% 
  filter(type == 'work', is.na(exclude)) %>%
  mutate(what = glue("<span class='cv-entry-title'>{what}</span>, {where}<br>", 
                      "{additional_info}<br>"
                     )) %>% 
  select(year, what) %>% 
  kable()
```
## Conference abstracts
```{r}
publications %>%
  filter(type == "conference paper") %>% 
  # insert appropriate icon for paper awards (and start with a line break)
  mutate(award = case_when(
    !is.na(award) & str_detect(award, "honourable") ~ glue("<br><i class='fas fa-award'></i> <span class='publication-award'>{award}</span>"),
    !is.na(award) ~ glue("<br><i class='fa fa-trophy'></i> <span class='publication-award'>{award}</span>"),
    TRUE ~ ""
  )) %>% 
  # create citations
  mutate(citation = glue("<span class='cv-entry-title'>{title}</span><br>",
                         "<span class='publication-authors'>{authors_full}</span><br>",
                         "<span class='publication-venue'>{venue_abbrev}{venue}</span>{award}")) %>% 
  # number entries with a prefix
  padding_function(., "C") %>% 
  blank_year_when_repeated() %>% 
  select(year, citation) %>%
  knitr::kable()
```
## Service
```{r}
cv_entries %>% 
  filter(type == 'service') %>% 
  mutate(where = if_else(!is.na(url), glue("[{where}]({url})"), where)) %>% 
  mutate(what = glue("<span class='cv-entry-title'>{what}</span> {where}")) %>%
  arrange(desc(date_end), desc(date)) %>% 
  select(year, what) %>% 
  kable()
```
## Awards
```{r}
cv_entries %>% 
  filter(type == 'awards') %>% 
  mutate(what = glue("<span class='cv-entry-title'>{what}</span> {where}<br>",
  "{additional_info}")) %>%  
  blank_year_when_repeated() %>% 
  select(year, what) %>% 
  kable()
```
## Volunteering
```{r}
## Personal skills & volunteering {.packages}
cv_entries %>%
  filter(type == 'volunteering') %>%
  mutate(what = glue("<span class='cv-entry-title'>{what}</span>, {where}")) %>%
  mutate(what = if_else(!is.na(additional_info), glue("{what}<br>{additional_info}"), what)) %>%
  arrange(desc(date), desc(date_end)) %>% 
  select(year, what) %>%
  kable()
```
## Skills
**Programming---**
R (advanced), Stata (advanced)


**Languages---**
English (native), German (conversational), Spanish (conversational)


<!-- <br class="pageBreak"> -->

## Research dissemination
```{r}
cv_entries %>% 
  filter(type == 'media') %>%
  select(year, what) %>% 
  kable()
```


### Links

```{r eval = FALSE}
publications %>%
  filter(type == "journal article") %>% 
  mutate(citation = glue("<span class='cv-entry-title'>{title}</span><br>",
                         "<span class='publication-authors'>{authors_full}</span><br>",
                         "<span class='publication-venue'>{venue_abbrev}{venue}</span><br>",
                         "<span class='publication-url'>{url}</span>")) %>% 
  padding_function(., "J") %>% 
  blank_year_when_repeated() %>%
  select(year, citation) %>%
  knitr::kable()
```


<!-- close 'cv-entries' div -->
</div>
